services:
  db:
    image: postgres:15
    container_name: postgres
    restart: always
    volumes:
      - data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - local-network # чтобы получить доступ из других контейнеров "db:5432", todo: удалить этот каментарий науй

  telebot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telebot
    restart: always
    volumes:
      - static:/static
    depends_on:
      - db
      # - api_server
    env_file:
      - .env
    networks:
      - local-network

  # api_server:
  #   build:
  #     context: api_server
  #     dockerfile: Dockerfile
  #   container_name: flask_server
  #   restart: always
  #   ports:
  #     - "80:5000"
  #   depends_on:
  #     - db
  #   env_file:
  #     - .env

networks:
  local-network:
    driver: bridge


volumes:
  static:
  data: